import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const coreFiles = [
  "scripts/core/env.js",
  "scripts/core/safety.js",
  "scripts/core/http.js",
  "scripts/core/store.js",
  "scripts/core/parser.js",
  "scripts/core/runner.js"
];
const sites = {
  psnine: {
    name: "PSNINE 每日签到",
    mitm: "psnine.com, www.psnine.com",
    module: "modules/psnine.sgmodule"
  },
  keylol: {
    name: "Keylol 每日登录",
    mitm: "keylol.com",
    module: "modules/keylol.sgmodule"
  },
  linuxdo: {
    name: "Linux.do 账号 A 自动浏览",
    mitm: "linux.do, connect.linux.do",
    module: "modules/linuxdo.sgmodule"
  },
  gamer: {
    name: "Bahamut 每日任务",
    mitm: "www.gamer.com.tw, api.gamer.com.tw, guild.gamer.com.tw, ani.gamer.com.tw",
    module: "modules/gamer.sgmodule"
  }
};

function scriptHeader(site, meta) {
  return [
    "/******************************",
    `脚本功能：${meta.name}`,
    "生成方式：tools/build-modules.mjs",
    "",
    "Surge 请优先安装对应 .sgmodule；模块会自动关联脚本并追加 MITM hostname。",
    "",
    `[module]`,
    meta.module,
    "",
    "[MITM]",
    `hostname = %APPEND% ${meta.mitm}`,
    "*******************************/"
  ].join("\n");
}

fs.mkdirSync(path.join(root, "scripts/dist"), { recursive: true });

for (const [site, meta] of Object.entries(sites)) {
  const parts = [
    scriptHeader(site, meta),
    "/* Auto-generated by tools/build-modules.mjs. Edit scripts/core or scripts/adapters instead. */",
    ...coreFiles.map((file) => fs.readFileSync(path.join(root, file), "utf8")),
    fs.readFileSync(path.join(root, `scripts/adapters/${site}.js`), "utf8"),
    "(function(global){ global.AutoSignCore.runRegistered('" + site + "'); })(typeof globalThis !== 'undefined' ? globalThis : this);"
  ];
  fs.writeFileSync(path.join(root, `scripts/dist/${site}.js`), parts.join("\n\n"));
  console.log(`built scripts/dist/${site}.js`);
}
