import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const coreFiles = [
  "scripts/core/env.js",
  "scripts/core/safety.js",
  "scripts/core/http.js",
  "scripts/core/store.js",
  "scripts/core/parser.js",
  "scripts/core/runner.js"
];
const sites = ["psnine", "keylol", "linuxdo", "gamer"];

fs.mkdirSync(path.join(root, "scripts/dist"), { recursive: true });

for (const site of sites) {
  const parts = [
    "/* Auto-generated by tools/build-modules.mjs. Edit scripts/core or scripts/adapters instead. */",
    ...coreFiles.map((file) => fs.readFileSync(path.join(root, file), "utf8")),
    fs.readFileSync(path.join(root, `scripts/adapters/${site}.js`), "utf8"),
    "(function(global){ global.AutoSignCore.runRegistered('" + site + "'); })(typeof globalThis !== 'undefined' ? globalThis : this);"
  ];
  fs.writeFileSync(path.join(root, `scripts/dist/${site}.js`), parts.join("\n\n"));
  console.log(`built scripts/dist/${site}.js`);
}
